//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 增删改查.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookInfo
    {
        public int BookId { get; set; }
        public string BookTitle { get; set; }
        public string BookContent { get; set; }
        public Nullable<int> TypeId { get; set; }
    
        public virtual BookType BookType { get; set; }
    }
}
